version: '2'
services:
    basketballteammanager-app:
        image: basketballteammanager
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://basketballteammanager-postgresql:5432/basketballTeamManager
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    basketballteammanager-postgresql:
        extends:
            file: postgresql.yml
            service: basketballteammanager-postgresql
