version: '2'
services:
    basketballteammanager-postgresql:
        image: postgres:9.6.2
        # volumes:
        #     - ~/volumes/jhipster/basketballTeamManager/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=basketballTeamManager
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
